linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/jose/caddy-serverless
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  disable:
    - gochecknoglobals
    - gomnd
    - lll
    - maligned
    - prealloc

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration