name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Install xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    
    - name: Validate plugin builds
      run: |
        xcaddy build \
          --with github.com/jose/caddy-serverless=.
        ./caddy list-modules | grep -q serverless
    
    - name: Run tests
      run: |
        go test -v -race ./...
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build release binaries
      run: |
        # Build example Caddy binaries with the plugin for different platforms
        mkdir -p dist
        
        # Linux AMD64
        GOOS=linux GOARCH=amd64 xcaddy build \
          --with github.com/jose/caddy-serverless@${{ github.ref_name }} \
          --output dist/caddy-linux-amd64
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 xcaddy build \
          --with github.com/jose/caddy-serverless@${{ github.ref_name }} \
          --output dist/caddy-linux-arm64
        
        # Darwin AMD64
        GOOS=darwin GOARCH=amd64 xcaddy build \
          --with github.com/jose/caddy-serverless@${{ github.ref_name }} \
          --output dist/caddy-darwin-amd64
        
        # Darwin ARM64
        GOOS=darwin GOARCH=arm64 xcaddy build \
          --with github.com/jose/caddy-serverless@${{ github.ref_name }} \
          --output dist/caddy-darwin-arm64
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 xcaddy build \
          --with github.com/jose/caddy-serverless@${{ github.ref_name }} \
          --output dist/caddy-windows-amd64.exe
    
    - name: Upload release binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/caddy-*
        body: |
          ## Pre-built Caddy binaries with Serverless Plugin
          
          These binaries include Caddy with the serverless plugin pre-built.
          
          ### Usage
          Download the appropriate binary for your platform and run:
          ```bash
          chmod +x caddy-linux-amd64  # Make executable (Linux/macOS)
          ./caddy-linux-amd64 run --config your-caddyfile
          ```
          
          ### Building from source
          ```bash
          xcaddy build --with github.com/jose/caddy-serverless@${{ github.ref_name }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}